language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- git submodule add git://github.com/danielfrg/pelican-ipynb.git plugins/ipynb
script:
- make github
env:
  global:
  - secure: $GH_TOKEN
